version: "3.9"

services:

  portal-ui-service:
    container_name: portal-ui-service
    image: portal-ui-service:1.0.0
    build: ../portal-ui-service
    environment:
      - AUTH_SERVICE_URL=http://auth-service:3000
      - NEXT_PUBLIC_KEYCLOAK_BASE_URL=http://localhost:8080/realms/south-wire
      - NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=south-wire-client
      - NEXT_PUBLIC_UI_BASE_URL=http://localhost/callback
    ports:
      - 80:80

  authentication-service:
    container_name: authentication-service
    image: authentication-service:1.0.0
    build: ../authentication-service
    environment:
      - KEYCLOAK_BASE_URL=http://keycloak:8080
      - KEYCLOAK_CLIENT_ID=admin-cli
      - KEYCLOAK_CLIENT_SECRET=huj4HGoM2vJRkqU3nmH3yyscgMv9qVLF
      - KEYCLOAK_REALM=south-wire
      - SWAGGER_BASEURL=http://localhost
      - SWAGGER_SERVER_NAME=Docker Compose Environment

    ports:
      - 3000:3000

  document_processor:
    container_name: document_processor
    image: document_processor:1.0.0
    build: ../document_processor
    environment:
      - GOOGLE_API_KEY=AIzaSyCYDWI5vwhCPjqyzyLq135hElz2gnwABQU 
      - SWAGGER_BASEURL=http://localhost
      - SWAGGER_SERVER_NAME=Docker Compose Environment

    ports:
      - 5001:5001


  keycloak:
    container_name: keycloak
    image: keycloak-service:1.0.0
    build: ../keycloak-service
    environment:
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_DB=postgres
      - KC_DB_URL_DATABASE=postgres
      - KC_DB_URL=jdbc:postgresql://keycloakdb:5432/postgres
      - KC_HOSTNAME_ADMIN_URL=http://localhost:8080/
      - KC_HOSTNAME_URL=http://localhost:8080/
      - KC_HOSTNAME=http://localhost:8080/
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB_URL_HOST=keycloakdb
      - KC_DB_URL_PORT=5432
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - PROXY_ADDRESS_FORWARDING=true
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
      - QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY=true
      - KC_PROXY_HEADERS=xforwarded
      - KC_TRANSACTION_XA_ENABLED=true
    entrypoint: "/opt/keycloak/bin/entrypoint.sh"
    ports:
      - 8080:8080

    depends_on:
      - keycloakdb

  localdb:
    container_name: localdb
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloakdb:
    container_name: keycloakdb
    image: postgres:16
    ports:
      - 55432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

    volumes:
      - keycloak_data:/var/lib/postgresql/data

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  pgdata: {}
  keycloak_data: {}
  zookeeper_data:
